- name: This will create a user for the DB to login to the system
  vars:
    user_name: dbuser
  user: rhenness
  hosts: tag_adduser
  become: yes
  tasks:
    - name: Add the User
      user:
        name: "{{ user_name }}"
        shell: /bin/csh
        password: "{{ user_password }}"
        comment: Temp DB User
        state: present
    - name: Change the SSH config to allow Password Logins
      lineinfile:
        path: /etc/ssh/sshd_config
        line: 'PasswordAuthentication yes'
        regexp: '^PasswordAuthentication no'
    - name: Restart the sshd service
      service:
        name: sshd
        state: restarted
